#/bin/bash
# -- Datos para el sistema de colas ---
#
# Nombre del trabajo ( opcional, no hace falta ponerlo ).
#$ -N alpha-0.88
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -q all.q
# -- Fin ---

#-- Definicion de variables de ambiente
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
intel_install_dir=/share/apps/install-intel-2011/composerxe-2011.2.137
export LD_LIBRARY_PATH=$intel_install_dir/mkl/lib/intel64:$intel_install_dir/compiler/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/share/apps/install-intel-2011/composerxe-2011.2.137/compiler/lib/intel64:$LD_LIBRARY_PATH
source /share/apps/gromacs/4.5.4/icc/bin/GMXRC.bash

#-- Ruta de los ejecutables
gems=/home/ecastillo/.local/src/GeMS/src/gems

#-- Ejecucion de su programa

$gems gems.gms
